### ISSUE TITLE
Add a "registerData" command to the daemon and client

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#117]
A transaction is created that puts the data in the arbitrary data field and pays the transaction fee,, a wallet needs to be unlocked for this to work off course.
Documentation on how to do this through the api is required as well

**Comment by LeeSmet** [comment]
Since we already have the sendcoins command its probably best to see if there is a way to add an optional flag to this command to set the arbitrary date first

**Comment by robvanmieghem** [comment]
@LeeSmet Would be a possibility but sendcoins is also a specialization of "create transaction".
I think it is more clear for users to have a seperate command, especially considering the importance tfchain gives to this feature.

**Comment by GlenDC** [comment]
I do agree with what @robvanmieghem says here now, it might be useful to have it as a separate commands. It would also allow us to add any logic custom to registration of data, in the near future. The command could be called `RegisterData`, but I'm open to the naming.

**Comment by LeeSmet** [comment]
Allright, lets go with the separate command then. Do we also allow sending coins here or do we try to only register data (not sending coins except for the minerfee if possible, or the minimum we need to send otherwise)?

**Comment by GlenDC** [comment]
> Do we also allow sending coins here

It's funny you mention, as we did also think about that possibility. I think we should allow to also add an extra amount of coins to be send. As there might be some use-case somewhere for that, but I can't think of any from the top of my hat.

**Comment by robvanmieghem** [comment]
Since registerdata is a convenience function, I would keep it like that f for now. Should the need arise to do both, lets see where to add it ( here, the sendcoins command or a  new one,...) And indeed, the minerfee should be added.

**Comment by GlenDC** [comment]
> Since registerdata is a convenience function, I would keep it like that for now

This sentence confuses me, what exactly do you mean?

**Comment by robvanmieghem** [comment]
not adding functionality not required right now

**Comment by GlenDC** [comment]
> not adding functionality not required right now

So just having the registerData handle data, rather than also allowing it to send some extra coins on top of that?
