### ISSUE TITLE
log the correct chain name in the logfiles

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#118]
currently it always says`rivined`:
`2018/03/04 11:18:59.390258 gateway.go:219: STARTUP: Logging has started. Rivined Version ....`

**Comment by lafont-e** [comment]
Rob, I'm looking at this issue and Rivined is hardcoded on log.go:76 so the only options are 
* change it to the name you like
* create a global variable with the name and use it instead
* eliminate the name

**Comment by robvanmieghem** [comment]
@lafont-e  In a Rivine implementation, this gets set like in https://github.com/threefoldfoundation/tfchain/blob/master/cmd/tfchaind/main.go#L18

**Comment by lafont-e** [comment]
I tried to use daemon.DaemonName in persist/log.go  and there is an import cycle with the package daemon when used in the package persist that I'm not able to see.

So I propose to change the name Rivined to os.Args[0] in log.go, this way you will get the right name, well if no one changes the executable name

If you agree I can push a PR

**Comment by GlenDC** [comment]
> I tried to use daemon.DaemonName in persist/log.go and there is an import cycle with the package daemon when used in the package persist that I'm not able to see.

those globals shouldn't even exist

> So I propose to change the name Rivined to os.Args[0] in log.go, this way you will get the right name, well if no one changes the executable name

cannot do that, as rivine is a library, we do not know what the user really wants to achieve with it

**Comment by lafont-e** [comment]
As this constant should not be there but a place to name the library must exist, maybe moving DaemonName to types/constants could an acceptable solution?

**Comment by GlenDC** [comment]
It is not, as I want to get rid of all globals, over time. Thus adding yet another global (or moving it) is stagnating or going in the opposite direction.
