### ISSUE TITLE
Provide the ability to replicate specific data on an external redis-protocol KV storage

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#120]
There still has to be a lot defined in this issue, but we can already outline the goal:

> Be able to filter on one or multiple addresses, and store the data (mapped to those addresses) in a KV storage. The storage is externally and accessed via [the Redis protocol](https://redis.io/topics/protocol).

By default it would do this for the entire blockchain (for which the addresses match), but I think it shouldn't be too difficult to support an optional min/max blockheight as well, should this be desired.

The original idea was to simply add it as an optional feature to the explorer module, given that it is already doing partially the work that has to be done. However @robvanmieghem came up with the idea, that we could just turn this into a separate binary, which uses the consensus and gateway modules, and which would run as a separate daemon service just for this purpose. I quite like that idea as well.

Also to be clear, for now there is no requirement to filter on data, I think the data should be considered arbitrary data, and filtering only ever happens based on addresses (sender and/or receiver(?)).

Prior to this issue #117 has to be resolved in master.

**Comment by GlenDC** [comment]
But does it allow to do this for multiple addresses at once? As it would be a waste of resources if we need to scan the entire blockchain for each address, separately.

**Comment by LeeSmet** [comment]
If you are referring to getting the current api call, the explorer (and consensus set) should have the unlockhashes stored in a bucket. So its just some database calls

**Comment by GlenDC** [comment]
The goal is that services can subscribe to a (local(?)) explorer node, such that all data send to specific 
addresses is also forwarded to those subscribed services. When a service starts subscribing for a given address, it will receive already all data that has been send since the specified min heigh/time or even from the genesis block, should no beginning have been specified.

## High level requirements and principles

+ be able to subscribe to the blockchain for a given address:
    + immediately this would give you all data send to that address up til now;
    + it would give you the data send to that address from then on, in real time;
+ data (also called records) will be replicated per address, where each address can be seen as a namespace;
+ each record has a unique ID:
    + this ID has to be ordered, only be 32 or 64 bit, unsigned (?);
    + this ID can be generated by the data replicator code which receives the data in order anyhow;
    + Open questions:
        + should we somehow keep a link between this unique ID and the actual hash?
        + how is this new ID useful, other than that it takes less space? As in, what meaning does it really give just by seeing it? Or is that last question a wrong question?
+ when subscribing an address it should also be possible to define a specific data from which to start;
    + thus a subscriber _has_ to provide the address and optionally _can_ provide a min block to start from (if not given it will start searching from the genesis block);
    + Open Questions:
        + this was suggested by KDS, but I wonder if it would be useful to (also) allow a from_block_height, in case both are given we could simply use the value that results in the oldest block to start from;
+ if some record with the same ID has already been replicated prior, it will simply be overwritten if newer data with the same ID is somehow replicated:
    + Open Question: how can this even happen?
+ for sending data there would be a specific minimum transaction fee, which for example in ThreeFold might be 0.1 TFT (to start which, as this could be modified later);
+ this would mean the owner of the data (the one that owns the address (=namespace)) would get paid for putting data in a namespace.

Open Questions:

+ How to prevent malicious actors from spamming random data to those addresses. Sure it would cost them money, but still, you would have crap in your namespace (forever);
    + or is this not a concern, and if not, why not?

## format of data which is binary stored in the blockchain (as suggested by kds)

```
[system_byte][id=4byte][acl=optional][payload]
```

- payload is opaque to blockchain;
- system byte defines whether or not ACL is to be used;
- if acl is used (system byte = 0) we would have a structure in the next bytes, prior to the payload;
- id is incremental id for each record;

Implications of this suggestion:

+ it would mean that the generation of the ID is the responsibility of the user sending the data;
+ we would require a fixed format of the data (except for the payload part which is still opaque);
+ we would have to support some ACL struct (but what would it really define/contain???);

This is different from how I saw it, as I had planned to just keep the entire arbitrary data opaque (except for the fact that we know we have to base64-decode it first and remove the prefix).

## implementation possibilities

Here we have several options. We could for example (a) expose this API over web sockets, allowing services to subscribe and receive data like that. However that would be an indirect approach. For example, for our use cases we wish to replicate to a (local) redis(-ish) server, meaning we would need to write another service, run that as well, having the data needless having to go through an intermediatary.

We could instead provide the option (b) to give the address(es) of redis server(s), such that the explorer replicates directly to those addresses data when given, over a TCP connection. While that is a more straight-forward and performant solution, it also doesn't give any flexibility. The user would have no way to define how it would want that data stored, nor how it should be processed prior to storage. Further it would force people to use the redis-based replication, while others might prefer to use something else that doesn't support the redis protocol.

A last (?) option (c) could be to provide a seperate "data replicator" binary. Due to the modular design of Rivine it should be possible to use (only) the needed modules (e.g. explorer) in order to look up old(er) transaction(s) for a specific address as well as make sure to stay in sync with the blockchain at all times, such that specific incoming transactions can also be consumed. If this is indeed possible it should allow us to provide this seperate binary to allow people to setup a node that would only do data replication (and thus only ever read from the blockchain) and nothing else.

### So many options...

In option (c) we could design the code such that subscribers are represented by an interface. This would allow anyone to provide their own specific data replicators, without having to define the entire read-and-spread logic themselves, given that they fork-modify-and-compile the binary.

As people would be forced to fork-modify-and-compile the binary anyhow, we could just as well make it just an optional feature into the regular daemon. Still I think this data-replication feature is something that will most likely be used stand-alone by a node/machine which is destined only for the data replication onto the KV storage server which is most likely running on that same node/machine, unless it's replicating to a cluster I suppose.

An entirely different approach (d) could be to have this as a seperate data-replication module, which would simply become another consensus-user, just as the explorer is one. This way we could make it another optional module that one could use, and would also not mangle the data-replication feature together with the exlorer one. At the same time it would allow both features to be used at the same time, togethe with any other already available feature. Just as with option (c) this would mean that people would have to fork-modify-and-compile the binary should they want their custom replication logic.

Somehow I like this last option, (d), the most. Should we go for option (c) or (d) we still have several possible approaches:

+ We implement a direct replication to a TCP server which implements the redis protocol, forwarding it the data directly, without touching it at all (except to decode the base64 encoding as well as removing the prefix);
+ We implement a direct replication to a TCP server which implements the redis protocol, but allow an optional interface which would allow you to define how the data needs to be consumed (after the base64 decoding and NonSia prefix removal) prior to replication, this would require a soft fork however;
+ We provide a more generic subscription model (based on channels?), where anyone can provide subscribers, given that they implement a common interface. The default implementation (and provided together with rivine) could still do (direct) replication to a redis-protocol-supported server, but at least it would allow people to redefine this replication-specific logic, given that they are willing to soft fork once again;

**Comment by robvanmieghem** [comment]
-  .please define "data send to an address" in respect to a transaction, I think this is a pretty important definition since a  lot of the logic depends on that.  
- the format of the data:` [system_byte][id=4byte][acl=optional][payload]`, shouldn't we prefix this as well? It is implied  in the "So many options" first option but not earlier.

**Comment by GlenDC** [comment]
> the format of the data:[system_byte][id=4byte][acl=optional][payload], shouldn't we prefix this as well? It is implied in the "So many options" first option but not earlier.

Yes, it has to be prefixed. I'll edit my comment. In the next few weeks it should be possible for blockchain implementations to define this prefix though.

> please define "data send to an address" in respect to a transaction, I think this is a pretty important definition since a lot of the logic depends on that.

How you mean? I might misunderstand your question, but when we talk about data send to an address I'm simply talking about a transaction created on the blockchain with the destination being that address. I might misunderstand your question though...

**Comment by robvanmieghem** [comment]
@GlenDC  Well, you can send tokens to an address, being the unlockhash of an output but data is just a property on a transaction that can have multiple token outputs.

**Comment by GlenDC** [comment]
> Well, you can send tokens to an address, being the unlockhash of an output but data is just a property on a transaction that can have multiple token outputs.

Well it's why I want to involve you all in defining this issue, as this is indeed very true. I suppose it would mean that data could be "send" to multiple addresses at once? I don't think there is a reason we should somehow add something on top, to make the address just be owned by one specific address?

**Comment by GlenDC** [comment]
While having the "replicator" and explorer be different modules could be nice, code-seperation wise, it would mean that a user wishing to both use the `explorer` and "replicator" module in a single daemon has the data twice, while probably this data is similar, so perhaps we should have it just be part of the normal explorer module after all, and be it opt-in.

**Comment by GlenDC** [comment]
It is important that the developer using that replication-enabled daemon, only ever has to interface using redis (rather than using a tfchainc CLI client for example). The daemon will still have to be running, and a wallet should be there (as otherwise transactions can't be made), but the developer's server will only ever communicate using the redis interface. Meaning that the "replicator" module has to somehow also watch the redis server (where the data will be replicated onto), to listen to the subscribe-related commands. This keeps it very simple for a user of that replicator to control it, as there is only 1 interface to learn: the redis one.

https://redis.io/topics/pubsub could help in this, but I'm not too sure. A queue implementation is possible as well.

**Comment by GlenDC** [comment]
The unique ids are based on the order that the blocks are stored on the blockchain, and are generated on-the-fly by replicators when replicating the data from the blockchain onto the redis server.

**Comment by GlenDC** [comment]
The originally proposed format `[NonSia][system_byte][id=4byte][acl=optional][payload]` no longer applies and instead you can just store it as expected as `[NonSia][payload]`.

**Comment by LeeSmet** [comment]
>While having the "replicator" and explorer be different modules could be nice, code-seperation wise, it would mean that a user wishing to both use the explorer and "replicator" module in a single daemon has the data twice, while probably this data is similar, so perhaps we should have it just be part of the normal explorer module after all, and be it opt-in.

Not sure if duplicate data is that big of an issue, as we will mainly be storing only the data coupled with an unlock hash. Moving it into the explorer module also means all the bolt code has to be separated, moved under an interface, and then the interface implemented for redis. Which seems tedious given the timeframe, and vulnerable to introduce bugs.

>It is important that the developer using that replication-enabled daemon, only ever has to interface using redis (rather than using a tfchainc CLI client for example). The daemon will still have to be running, and a wallet should be there (as otherwise transactions can't be made), but the developer's server will only ever communicate using the redis interface. Meaning that the "replicator" module has to somehow also watch the redis server (where the data will be replicated onto), to listen to the subscribe-related commands. This keeps it very simple for a user of that replicator to control it, as there is only 1 interface to learn: the redis one.
>
>https://redis.io/topics/pubsub could help in this, but I'm not too sure. A queue implementation is possible as well.

So if I understand you correctly, there should also be a redis interface which can do the same as our client right now? Thats way outside the scope of this issue, and probably needs some discussion as well

>The unique ids are based on the order that the blocks are stored on the blockchain, and are generated on-the-fly by replicators when replicating the data from the blockchain onto the redis server.

Do they still need to be ordered? Then we'd need some scheme like `blockheight-txindex-part_of_hash`. Given the constraint to the ID size, that probably boils down to (32bit blockheight -32bit txnindex)

**Comment by GlenDC** [comment]
>  Moving it into the explorer module also means all the bolt code has to be separated, moved under an interface, and then the interface implemented for redis. 

I don't think that's true, as we would still want a local database to get already fetched blocks from, to have faster look ups for new subscribers. As remember, when they subscribe we need to give them also all data already send to an unlock hash in the past.

> So if I understand you correctly, there should also be a redis interface which can do the same as our client right now? Thats way outside the scope of this issue, and probably needs some discussion as well

No, we don't want all our client functionality over a redis interface. What we (apparently) want is that the user would subscribe to an address using their redis client, this would probably be added to some kind of queue, and the replicator will pick up this request from the redis server, so it knows it has to start replicating the data for that address to the redis server. That subscribe request would define the address as well as the "from_date".

> Do they still need to be ordered? Then we'd need some scheme like blockheight-txindex-part_of_hash. Given the constraint to the ID size, that probably boils down to (32bit blockheight -32bit txnindex)

Why is that needed? The data has a natural order order on the blockchain, no? When we collect data to be replicated, we would do so in order as well, no?

**Comment by GlenDC** [comment]
> If we keep the local boltdb, then there is little to no gain in terms of storage space.

I was talking that if we would go for 2 separate modules, and thus which their own boltdb database, you would have twice as much data, while if we merge this logic directly as an opt-in feature into the explorer, we would only have that data once.

> A misunderstanding on my part then. For now I'll focus on storing ALL the data, and once that is working, start on subscribing

Sounds good, just make sure to know that for KDS both are required for the launch, as he really wants the user of that replication feature (developer of the server that consumes that replicated data), only has to work with one interface (a redis client).

> Or do we simply use the txnID?

I don't think KDS really minds what ID generation we use, as long as it has the following properties:

+ it is only 32 or 64 bit (thus small);
+ it is ordered (where the order HAS to be the same order as the data is stored into the blockchain);
+ each ID has to be unique to each record (data);
+ when 100 replicators replicate the data of the same namespace (address) from the same blockchain, it should all generate the same IDs for the same record;

**Comment by LeeSmet** [comment]
> I was talking that if we would go for 2 separate modules, and thus which their own boltdb database, you would have twice as much data, while if we merge this logic directly as an opt-in feature into the explorer, we would only have that data once.

I see what you mean, but I wasn't planning on keeping a local boltdb. Sure it would be nice since this way the data is indexed already in case we connect to a second redis instance, but for now that would also mean adding some complexity in the syncing, which we can also do later when we have more time for this (if we even want to continue with this setup in the future)

> just make sure to know that for KDS both are required for the launch

yeah, problem is my experience with redis is very little so I'll need to do some research first

as for the ID generation, I think I'll go with 32bit blockheight + 32bit index in the block of the transaction for now. That way all the required properties are statified

**Comment by GlenDC** [comment]
> yeah, problem is my experience with redis is very little so I'll need to do some research first

If so, please try to already replicate it for now, which is as simple as a `HSET` call to a given server (where the key is the address and the field the ID), that should be simple enough with limited experience with Redis.

I'll try to think tonight and allocate some time to come up with a plan to also handle the subscription using redis, so that you don't lose too much time in researching that.

> as for the ID generation, I think I'll go with 32bit blockheight + 32bit index in the block of the transaction for now. That way all the required properties are statified

To be honest, for me that sounded like an awesome plan. But it seems that the requirements _really_ are that it has to be 32 bit. So I don't think it will be allowed.

Not sure if you know how to make a similar scheme work (safely) for 32 bit? Otherwise we'll really somehow to just keep a counter, which is deterministic as long as you start counting from the genesis blockheight and only increase the counter for each record per address.

**Comment by GlenDC** [comment]
By the way, not sure if I communicated this in the meanwhile properly, but the address is indeed the  address which receives the fee via the output (and thus the receiver address). If there are multiple addresses so be it, as long as they all receive that data transaction fee, it is OK I guess.

**Comment by LeeSmet** [comment]
> If so, please try to already replicate it for now, which is as simple as a HSET call to a given server (where the key is the address and the field the ID), that should be simple enough with limited experience with Redis.

Yeah, HSet is one of the few things I do know, so already doing that.

As for the subscription, we could store an HSET somewhere which has the addresses we follow as field and a consensuschangeid as value. That way we can register every address as its own subscriber to the consensusdb. This would solve the issue of managing all the different addresses which may not be in the same state. Though I'm not sure how manageable this will get. Ideas are always welcome ofcourses

As for the ID to become 32 bit, I'm not sure. Obviously I could shrink it a little bit, but I'd need to check how much txns can fit in a single block to see how small I can make the index part, and we still need a reasonable number for the blockheight part so it does not overflow in this scheme. Counting from genesis could work, but then we always need to start at genesis, not at an arbitrary position

**Comment by GlenDC** [comment]
> obviously I could shrink it a little bit, but I'd need to check how much txns can fit in a single block to see how small I can make the index part, and we still need a reasonable number for the blockheight part so it does not overflow in this scheme. 

Yeah no, I don't think that's a good idea. As I said I would be totally happy to go with your scheme, but alas, it seems for some reason 8 bytes is not good enough. 4 bytes it is.

> Counting from genesis could work, but then we always need to start at genesis, not at an arbitrary position

Yes, that would indeed mean that. Obviously for each subscription that only needs to happen once, after that you can just keep counting based on the last ID in redis, I would assume. You can also store values used for replication in redis, I don't think that's an issue either.

And given that walking over the blockchain are local DB calls, having to start from the genesis now and then, doesn't seem like it's that bad of a thing either, or is it?

**Comment by LeeSmet** [comment]
> 4 bytes it is.

I'm curious, did you get any reason why we go with 32 bit fields in a 64 bit era?

In the scheme I have in mind, where each "tracked" address runs as its own subscriber, we'll indeed need to count from genesis every time, loop over every block and every txn in those blocks. But we need to do that anyway since we want to get all the data out of it, so incrementing a counter while we store data over tcp to a possibly remote redis server won't impact performance if we look at the bigger picture

**Comment by GlenDC** [comment]
> I'm curious, did you get any reason why we go with 32 bit fields in a 64 bit era?

There doesn't seem to be a reason other than the fact that 32 bit seems the smallest integral value possible, while still allowing sufficient amount of unique IDs for a single namespace at once.

> In the scheme I have in mind, where each "tracked" address runs as its own subscriber, we'll indeed need to count from genesis every time, loop over every block and every txn in those blocks. But we need to do that anyway since we want to get all the data out of it, so incrementing a counter while we store data over tcp to a possibly remote redis server won't impact performance if we look at the bigger picture

It should indeed not need to hurt performance. However we have to make sure to not lose the deterministic property. Should you have a lot of independent subscribers for a single namespace, even if some subscribers start from different dates/block-heights, still should those subscribers all use the same UniqueID for the same transaction.

**Comment by GlenDC** [comment]
Sadly last night I didn't find time to work on a design around this feature any longer. However this morning I came up with a design which I think covers the entire "replicator" interface, using the Redis protocol as a (means to establish a) communication and storage medium.

The "replicator", when enabled, knows what to do thanks to the commands send to the "replication channel". When the "replicator" is enabled and activated it subscribes to that channel using `SUBSCRIBE replication`. The user would use this channel to indicate to the replication which address is to be (un)subscribed:

+ subscribe: `PUBLISH subscribe:$address[:$from_date]`
+ unsubscribe: `PUBLISH unsubscribe:$address`

> NOTE: as far as I know this doesn't allow to return an error back to the user,
> which might be desired in case the user publishes a misformatted/unknown menssage,
> or in case the action couldn't be applied for whatever reason.
> Not sure what the best solution would be for this.
>
> > One solution could be to have a second channel,
> > on which the replicator publishes negative/positive replies,
> > this seems the most sane solution, as you can have many subscribers as you want,
> > and they all receive the same published content.

> (!) the beautiful thing about channels is also that if you have no subscribers,
> you can still safely publish on the other side without having to be worried that you fill up space,
> as publish content is simply discarded if no subscriber is available,
> the `PUBLISH` command returns the amount of times it published that content,
> which is equal to the amount of active subscribers, and thus can be 0.

Replicated data is stored in a hashmap, and stored by the data "replicator":

+ each record is stored using the command: `HSET $address $uid <data>`
+ min/max indices are stored for a namespace as well:
    + start/min: `HSET $address s $uid`
    + end/max: `HSET $address e $uid`
    + this metadata relies on the assumption that all indices between start and end are used/stored;
    + having this metadata we can handle following situations:
        + subscribe starting from an index X lower than min:
          we simply have to store from X until min
        + subscribe starting from an index X in between min and max:
          we have to do nothing, storage wise
        + subscribe starting from an index X, after max:
          store starting from max+1, until we either reached X,
          or until we have no more records available

All this means that the user of the replicator has to
only support 4 redis commands (`HSET`, `HGET`, `SUBSCRIBE`, `PUBLISH`),
and it has enough to be able to communicate with "replicator",
as well as to consume the replicated data.

Obviously some other commands (e.g. `HMGET`, `HSCAN`, `HGETALL`, ...),
could be useful as well for the user, and would make more sense in certain situation,
but they still remain optional to be supported by the user,
and the interface could work fine just without. Even so,
this is all on the user side, and has no effect on the `replicator` side at all.

**Comment by LeeSmet** [comment]
> this metadata relies on the assumption that all indices between start and end are used/stored;

So this means that the `uid` is linked to the address (multiple addresses can have the same `uid` set), and that the `uid` is only incremented in case of a txn which contains the linked address in one of the outputs, and that the txn has arb data.

Is the range a hard requirement, or something that will need to be supported at some time? since it obviously adds (a lot of) complexity to the design.

Finally, how to store the data? Right now, arb. data on a txn is a `[][]byte`, whereas I store it as []byte, using the sia encoder to flatten it. this produces the followig output:

field: "\xe2\x8d\x93" -> the uint32 uid as bytes
data: 
"\x01\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00NonSia\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00testdata" -> siaencoder of 2 dimensional array, first 8 bytes indicate the size of the first array dimension is 1, next 8 bytes indicate the size of the first (and only) 2nd dimenstion byte array is x18, followed by the 16 prefix bytes (converting those that can be converted to valid chars), followed by the actual "testdata" which was inserted. 

Btw, the sia encoder encodes in little endian, while the `string(uint32)` builtin appears to convert to big endian. 

I was wondering if we can just flatten the arb data by appending each row to the previous, then we  don't have the overhead of the encoding, but we won't be able to reconstruct the 2 dimensional array (if this is ever required)

**Comment by GlenDC** [comment]
> Btw, the sia encoder encodes in little endian, while the string(uint32) builtin appears to convert to big endian.

You could convert numbers using the binary package as well.

> So this means that the uid is linked to the address (multiple addresses can have the same uid set), and that the uid is only incremented in case of a txn which contains the linked address in one of the outputs, and that the txn has arb data

Yes, I thought this was already clear, I guess not. Either way, I'm happy that requirement is clear and well understood now.

> Is the range a hard requirement, or something that will need to be supported at some time? since it obviously adds (a lot of) complexity to the design.

I think it is a useful feature to have, not sure if it is super important, but knowing that kds already freaks out about 4bytes vs 8bytes for an ID, I would say replicating all possible data, rather than a limited scope is very much out of the question.

What kind of complexity would it add? We already have the dates, so all it would mean is that we not only filter based on the address but also the date, right? Where the `from_date` is optional. If you have a better idea on how to provide the option to the user to provide a range, I'm all ears to, if that would make it easier.

> data on a txn is a `[][]byte`

That's weird, why is this doen? I would have made this a `[]byte` instead o.o
And i'm fairly sure KDS is expecting a flat binary payload as well.

Can you elaborate on why it is not a flat slice?

**Comment by LeeSmet** [comment]
Also, I suggest to change the `uid` in:

> + start/min: `HSET $address s $uid`
> + end/max: `HSET $address e $uid`

to use the consensuschangeid. Since the consensusset reports the block history as it happend, with rollbacks due to possible forks, which would mean that a uid can be generated twice

**Comment by GlenDC** [comment]
> As for subscription ranges, it means that the subscriber for an address needs to be aware of this. It needs to be able to unregister itself.

The subscriber might be aware from it, but this is not required. I do see where complexities can arise. At all times we can simply use the lowest chosen from_date, of any active subscriber. This min_from_date can be stored as metadata as well I suppose.

If there is a startdate, and this data is later adjusted to a lower value, we need to restart from genesis anyway since the uid needs to be calculated

Yes that is

> Since the consensusset reports the block history as it happend, with rollbacks due to possible forks, which would mean that a uid can be generated twice

Not sure that is a real concern, as that would simply mean we overwrite an existing ID with the actual transaction, which the design allows for. But if we can use `concensuschangeid` without having to give something up in return, than why not.

**Comment by GlenDC** [comment]
As discussed on telegram, we should only replicate data which is for sure is not going to be forked. This way the replicated data can be seen as WRITE-ONLY, with no data previously replicated suddenly deleted due to a fork.

**Comment by LeeSmet** [comment]
Updated the WIP branch with latest code, still need to test with actual data, will do that once I fixed my test setup. Management through redis ((un)subscribe) works.

- When closing the daemon, it hangs until redis throws a SIGSEGV, because the PubSub channel somehow gets garbage collected. It seems however that the library exposes a somewhat lower lvl API which allows us to get a read only buffered channel, so I'll change the current subscription strategy to make use of that
- Also right now data will be written immediatly (and still deleted), so there will need to be some delay(prevent deletes) and maybe caching (performance so we can use pipes, don't this is all that useful though once we've caught up).
- Check if there needs to be code cleanup since some of it might be out of place (or unused) after the latest requirements change

**Comment by GlenDC** [comment]
> Also right now data will be written immediatly (and still deleted), so there will need to be some delay(prevent deletes) and maybe caching (performance so we can use pipes, don't this is all that useful though once we've caught up).

Let's only replicate data, which transactions live in blocks that have at least <MaturityDelay> blocks after them.

---

Further requirements:

+ when using the data gets created using the REST API, the user should receive a long ID identifying that data (the transaction hash?), if this is already the case, excellent;

---

Open "Questions":

+ for now anyone would be able to create data for a given namespace, we need a way to restrict such access (an implementation based on the research done in #141 could help);

**Comment by LeeSmet** [comment]
> data gets created using the REST API

I suppose you mean a transaction is posted which has arbitrary data

As for the ID, we could return the txn ID to the user after a successful post. But that is a separate issue I feel as it does not seem to have anything to do with the replication feature itself (unless the ID's need to be linked somehow)

**Comment by GlenDC** [comment]
> I suppose you mean a transaction is posted which has arbitrary data

yes

> As for the ID, we could return the txn ID to the user after a successful post.

Yes that's what we should do. It has to do with the replication feature as we need to be able to return an ID immediately to the user of that REST API (and thus also the python light client), as the short ID (based on the blockchain order etc) will only be known once the transaction has both been pooled into a block, has been validated and accepted, and has survived long enough to guarantee its survival. At which point the data is replicated using the short ID. At that point however the user only has this long ID, so we need to be able to go from that long ID to that short ID. And thus those 2 IDs can be seen as a two different references to the same stored data.

**Comment by LeeSmet** [comment]
Is there an idea about this link already? if the data replication module needs to give some feedback or be able to resolve long IDs to short ones, it will need some kind of persistent mapping, since the short ID's have no relation to the actual location of the data

**Comment by GlenDC** [comment]
For now I have no precise idea about what to do, certainly not one I'm happy with. Just as you were thinking, with the current requirements in mind I do indeed think that such a link is only possible using some kind of persistent mapping. For example, a naive link could be easily established by using just the first __x__ bytes of the long id as the short ID. However this would break the ordered requirements of the short ID.

That said, I think it can be persistent and at the same time volatile. The short id could be communicated over a channel from server to user, using the same subscriber-kind-of system. At the same time we could also make sure that the first time the user requests data using the long ID, the new (short) ID is returned together with the data, and to from than on only accept the short ID (as we could at that point delete the link between the long and short).

However, I'm not sure you really have to worry about this for now. I think all parties involved would accept the non-existence of that short ID for now, and simply have the long ID for now.

@robvanmieghem might have some ideas/input/feedback for this in specific as well.

**Comment by GlenDC** [comment]
Good news. It has been agreed with KDS that we can use 8 bytes for the short ID. See #149 for more information. This means that this feature gets much simpler as well. Once issue #149 is implemented (any suggestions for the new endpoint URL mentioned at the end of that issue description by the way), we can rebase and integrate it in this feature as well.

It will make the mapping also much more obvious. Even though it will not resolve the mapping at all, and you will still need to find a way to map the long to the short IDs.
