### ISSUE TITLE
allow for different networks of the same type of blockchain

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#128]
We need to allow different networks using the same type of blockchain (that is to say the same (custom) rivine implementation), to connect to different networks, without mixing connections. For example if we have a prod and test net, we don't want to by accident create test blocks on the prod network.

Therefore we'll need to be able to configure the initial parameters (e.g. genesis related configs), as well as bootstrap nodes. This needs to be possible using a config file, but it should also be possible to have them embedded already. (e.g. it makes sense that the default is the production one, and that you could allow for a flag to the daemon as to allow to connect to the default test network instead).

This feature is required for tfchain, as can be seen in https://github.com/threefoldfoundation/tfchain/issues/3

**Comment by LeeSmet** [comment]
Doing this would mainly mean removing the genesis constants from the init function in the types package, and injecting them (through a new method). In theory we could also work with a map, which maps network names (strings) to genesisblocks, to allow more then 2 networks (e.g. a main network, a testing network, and a faster testing network (10s blocktime) which resets every month or so). Just an idea
