### ISSUE TITLE
improve published docker container of rivine

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#148]
+ [x] always make sure to have the `latest` tag available,
        which points to the last (stable) released container
+ [x] we shouldn't prefix versions with `v` (more details can be found in https://forums.docker.com/t/what-is-the-naming-conventions-of-docker-tag/34042/3)
+ [x] we need have a short and full description for the docker container

**Comment by LeeSmet** [comment]
first 2 issues done in 689afca6f481ff5603d1613abceb61887c791541, as for the other 2, I don't have access on the rivine docker account

**Comment by LeeSmet** [comment]
Updated the description of the rivine account
