### ISSUE TITLE
consensus Synced property is broken

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#152]
When running a full tfchain node, connected to the tfchain testnet, my `cs.Synced` property never gets set to True, even though I am probably synced.

**Comment by GlenDC** [comment]
Interesting. Please elaborate more when you have more information.

**Comment by lafont-e** [comment]
There is a delay hardcoded of 90 minutes to wait before accepting the sync is done, it waits to have more peers that can validate the blockchain, as the initial transfer is asked to all peers  on the gateway not all at the same time, there is a sleep time between request to a peer.

The transfer of blocks are done from history with 32 blocks max on every transfer, from those 32 blocks, the first 9 are the last ones, so you can continue pushing blocks to the consensus if needed, but after those 9, the 23 remaining are picked with a gap of a power of 2 in every selection, ie: height-10, height-10-2, height-10-2*2, height -10-2*2*2 .... until the height to select  become smaller than the gap (2*2*2 ...) ie: when height will become negative, and the last one is the genesis block.

So when transferring you receive the last 9 ( I presume this is done this way for the maturity delay)  and an assorted group of blocks from all over the remaining blocks to transfer.

**Comment by lafont-e** [comment]
And yes, after 90 minutes of my second syncing the synced flag switched to true.
So this is definitely not a bug,, but a feature

**Comment by GlenDC** [comment]
hmm, even though we wontfix this, I think we can do better in the reporting of that property, where it is very clear to why it is No, while we might as user think it should be Yes.

**Comment by GlenDC** [comment]
It turned out not be a bug, as @lafont-e found out. The next step, somewhere in the future, will try to do something about it, so we can prevent the confusion we currently have.
