### ISSUE TITLE
make one "coin" less hastings by default and configurable per blockchain

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#170]
Right now one "coin" (e.g. TFT) is 10<sup>24</sup> hastings, which is really a lot. Perhaps a value of 10<sup>9</sup> hastings would make more sense.

Further it might make sense to make this something that is configurable per blockchain, as certain implementations might have a different requirement for this.

**Comment by robvanmieghem** [comment]
Also, I vote against this milestone, we have more important things to do than lowering the granularity of a token split up.

**Comment by GlenDC** [comment]
Problem is, I do not see how you'll be able to change such a thing after the launch of a chain.

And let's talk on Monday about the current milestone planning, I don't think anything is written in stone. The more important thing is that we agree on the plan, which doesn't seem to be the case for now.

This issue was more of a suggestion/remark, not a demand or anything like that.

**Comment by LeeSmet** [comment]
As onecoin is defined as a global var in the types package, its probably best if https://github.com/rivine/rivine/issues/179 is resolved for that, which is done as part of https://github.com/rivine/rivine/pull/134.
