### ISSUE TITLE
spec out transactions 2.0

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#172]

**Comment by GlenDC** [comment]
Transaction:
+ [] CoinInput
+ [] CoinOutput
+ [] BlockstakeInput
+ [] BlockstakeOutput
+ ArbitraryData: []byte
+ PublicKey: []byte
+ Signature: []byte

```
encodedMessage :=  encoding(
		encoding(coinInputs),
		encoding(coinOutputs),
		encoding(blockstakeInputs),
		encoding(blockstakeOutputs),
		encoding(arbitraryData),
		encoding(pubKey)))
Transaction.Signature = ed25519.Sign(privateKey, encodedMessage)
```
> allows the transaction to be verified as:
> ```
> ed25519.Verify(
>	Transaction.PubKey, encodedMessage, Transaction.Signature)
> ```		                 

CoinInput:
+ UnlockType
+ UnlockFulfillment

CoinOutput
+ Value
+ UnlockType
+ UnlockCondition

— —————

SingleSignature Unlocking
===

unlockCondition = publicKey (== address of wallet)
unlockFulfillment = `ed25519.Sign(privateKey, encoding(coinOutput))`

Validation:

	ed25519.Verify(publicKey, encoding(coinOutput), unlockFulfillment)

——————


Script Unlocking
===

unlockCondition = conditionScript (what has to be done to spend coins)
unlockFulfillment = fulfillmentScript (push stuff onto the stack only)

Validation:

	1. empty stack
	2. run fulfillmentScript 
	3. run conditionScript

All steps have to exit without errors,
and conditionScript has to return `True`

further there are some additional rules:

+ op codes have to be valid
+ param instructions within an opcode have to be valid
+ fulfillment scripts can only push data to the stack, no other op codes can be used there
+ ...

**Comment by robvanmieghem** [comment]
@GlenDC looks good can you also define the transaction ID?
- It's unclear if the signature is on the transaction or on the input in the unlockFulfillment
>  Perhaps we could instead have just a generic TransactionInput and TransactionOutput,
with a CurrencyType as byte, which indicates if its about coins or blockstakes, ...?
Yes but considering the importance of blockstakes right now, don't want to have this selection everywhere. There are also different rules for coins and blockstakes. Yes, underneat you might serialize them like you propose.

**Comment by GlenDC** [comment]
Given https://github.com/rivine/rivine/issues/172#issuecomment-374014530, `Transaction::ID -> TransactionID` would be defined as:

```
func (t Transaction) ID() TransactionID {
    return TransactionID(crypto.HashAll(
        t.VersionNumber,
        t.CoinInputs,
        t.CoinOutputs,
        t.BlockStakeInputs,
        t.BlockStakeOutputs,
        t.ArbitraryData,
        t.PublicKey,
        t.Signature,
    ))
}
```

---

> Yes but considering the importance of blockstakes right now, don't want to have this selection everywhere. There are also different rules for coins and blockstakes. Yes, underneat you might serialize them like you propose.

You are right, let's for now just do it like that.
