### ISSUE TITLE
replace types/constants global variables with a config struct/system

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#179]
Currently the constants defined in `types/constants.go` are globals. This is bad as Rivine is a library and we cannot afford have constants like this, as it means we assume how the user will use it, while really we do not.

Instead it should simply be one or multiple config structs, which can be given to the relevant modules as properties (similar to what we already do since #164 for the name and version).

Right now we assign default values based build tags, and while that could still be done to create a default config or configs), it should not be forced upon the user.

So as an example if the default works fine for the use-case (as our defaults should be sane enough), one could do `types.DefaultBlockchainConstants() // -> BlockchainConstants`. However prior to using that, one could adapt it, or one could even create their own config entirely from scratch. We could even provide multiple Default funcs besides this that do the same for dev/standard/release/testing. Up to you.

No matter what, as long as those globals disappear and get turned into a local config, it's OK. 

In the end the Rivine API will just care it receives the right config value as a direct value, just as we also do with the BlockchainInfo.

**Comment by GlenDC** [comment]
@LeeSmet is already working on this as part of #134.

@LeeSmet check if you need to do something more in order to fully satisfy this issue as well, you can do it as part of the same PR, you were doing the work already anyhow.

**Comment by LeeSmet** [comment]
When you say "local config", do you mean an unexported global struct which holds the current exported globals, which would require creating accessor methods for all the values, or can it still be exported so the other modules can check the values directly

**Comment by GlenDC** [comment]
No, I am talking about a struct local to the modules that require it.

Look a the `BlockchainInfo` struct as an example: https://github.com/rivine/rivine/pull/164/files

So perhaps what we could do, inspired by PR #164, is add a `BlockchainConstants` struct, and than perhaps even a `BlockchainContext`, where the latter would compose the constants and info one. Feel free to rename it all to Chain instead of Blockchain if you think that's better.

Having this no longer global is no problem for the non-test codebase AFAIK. Fairly sure these constants are usually used from within one of the API modules already, and where it is not it should be do-able.

It's a simple enough change though, and one you can't really make mistakes in by accident, as the compiler and unit tests will just fail if you forget to modify a reference(-related thingie).

**Comment by LeeSmet** [comment]
A problem is that the client uses the `types.OneCoin` variable, but we can't inject that since setting these variables is done by the daemon. So there will need to be some other solution here

**Comment by GlenDC** [comment]
Closed by c27a073cf408b8b0d98f8b02a2ed848440fb4cee
