### ISSUE TITLE
provide consensus function to read transaction using its long ID

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#182]
It is already possible to fetch/read a transaction using its shortID (see: https://godoc.org/github.com/rivine/rivine/modules/consensus#ConsensusSet.TransactionAtShortID). Using the shortID is the most efficient, however when creating a transaction using SendCoins (also used to register Data), we only know the long ID (TransactionID). Therefore it should be possible to get a transaction of any user just using that ID.

The shortID should be returned as part of the returned transaction (should a transaction of the long ID (== transactionID) be found). This way next time the user can use the ShortID which is more efficient.

**Comment by LeeSmet** [comment]
Right now transaction ID's are not indexed in the consensus set. As such we'd need to loop over every block to see if txn matches the ID, and if the ID is not present we'll need to check the entire chain, which might take a long time depending on the size of the chain. So its best tto create a new bucket which maps long ID's to short ID's, as that should not take up a lot of space. Using this approach will make the long ID equally efficient to the short ID as well.
