### ISSUE TITLE
Return transaction info when creating transaction

### ISSUE THREAD

**Issue by lucasvanhalst** [rivine/rivine#185]
Currently, the POST /transactionpool/transactions endpoint doens't return any response data. It should return some information about the created transaction.

**Comment by robvanmieghem** [comment]
Please define 
>some information
but you already know everything as the transaction id is something you can calculate yourself
but that could be returned if really needed.

**Comment by lucasvanhalst** [comment]
The transaction id would be enough, since I don't think implementing it in javascript is a good idea, seems like a waste of time when it could just be returned here.
