### ISSUE TITLE
provide multi-signature contract

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#196]
Provide a lock type which allows money to be locked into its own unlockhash. That contract is managed by N people, and can only be released if at least 2/3 agrees on this release and the outputs the coins are supposed to go to.

**Comment by robvanmieghem** [comment]
@GlenDC Is there a functional demand for this or just a nice to have?

**Comment by GlenDC** [comment]
It's a real functional demand, details or how it would work aren't important to kds.

But he really does want to be able to define a kind of contract that allows to lock money, and only release if a sufficient amount of the members agree on the details (e.g. outputs).

It's a simple enough thing to be able to provide, there are a couple of ways I see this being possible, we would just need to agree on the best approach here.

Feel free to bring it up with kds though, if you think it requires more thought.

**Comment by GlenDC** [comment]
As I said earlier, it is needed in order to lock up most of the genesis money into one or multiple contracts, and only release some of it, to the farmers every x weeks/months. This would be managed by the TFT foundation I think, and thus about 100 people would be registered in those contracts, of whom 70 or so should at least agree.

**Comment by robvanmieghem** [comment]
In this case, there should be an issue in the tfchain repo describing the functional usecase, technical  rivine issues can then be created to realize the functional tf issue if needed. The discussion about how we want to solve the functional issue can first be done in the tfchain  issue, where it belongs, not here where we are going from a technical issue to a functional discussion.

**Comment by GlenDC** [comment]
Closing this issue, as we'll first need a functional issue in the tfchain repo.
