### ISSUE TITLE
gateway looks for outbound ip address

### ISSUE THREAD

**Issue by nvinken** [rivine/rivine#21]
When having 2 devices on the same network, the outbound address is seen different than the internal ip. 
When peering, the device want to peer with the outbound address and the internal ips and get confused.

**Comment by nvinken** [comment]
isMyLocalAddr should not be placed in upnp.

**Comment by GlenDC** [comment]
There seems to be an inconsistent use between the local and external IP address in the gateway code, making functionality and unit tests such as `TestPeers` fail.

**Comment by GlenDC** [comment]
The address returned from the `GET /gateway` endpoint also seems to be a local address, rather than an external one, thus not beng very useful, as that address can't be used to connect to a different peer.

**Comment by robvanmieghem** [comment]
Problem should be solved by https://github.com/rivine/rivine/issues/42
