### ISSUE TITLE
look into gateway issues

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#237]
+ why are gateways not sharing peers around?
+ why can nodes not automatically connect to bootstrap nodes?
+ ... ?

**Comment by LeeSmet** [comment]
Seems like the shareNodes rpc call only returns nodes which are marked as `outbound`

**Comment by LeeSmet** [comment]
So it seems that the shareNodes calls pulls from the nodes list. But nodes don't always seem to get added to this list (At the moment it seems only peers you connect manually are added as nodes as well). Therefore the bootstrap nodes are only broadcasting the addresses of some other ones. Say node A connected to node B, then node A will broadcast B's address, but not the other way round

**Comment by LeeSmet** [comment]
Now that one of the bootstrap nodes in the field has an outbound marked connection to a non bootstrap node, it indeed is also relaying this node's IP address to other peers. However, when my node on my local machine attempts to connect to this node, the connection fails

**Comment by LeeSmet** [comment]
It seems that after restarting the daemon, it automatically tries to connect to this node as well now, and this time the connection was successful

**Comment by LeeSmet** [comment]
Nodes running on the testnet with updated gateway code are stable. Testing shows that non bootstrap nodes are being connected to if they have unpnp enabled or are otherwise publicly reachable.
