### ISSUE TITLE
align atomic swap cli command terminology to decred atomic swaps

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#334]
btcatomicswap: 
```
 initiate <participant address> <amount>
  participate <initiator address> <amount> <secret hash>
  redeem <contract> <contract transaction> <secret>
  refund <contract> <contract transaction>
  extractsecret <redemption transaction> <secret hash>
  auditcontract <contract> <contract transaction>
```
In our case, the help  is 
```
initiate dest amount
participate dest amount hashedsecret
claim outputid secret [dest src timelock hashedsecret] amount
refund outputid [dest src timelock hashedsecret] amount [flags]
extractsecret outputid [hashedsecret]
```
I would be better to use the same terminology for the parameters and certainly  the  redeem command that changed in to "claim"
While we are at it, the participate outputs "Hashed secret", the decred tools use "Secret hash".

**Comment by GlenDC** [comment]
Sounds good. We have `audit` as well:

```
audit outputid|unlockhash dest src timelock hashedsecret [amount] [flags]
```

**Comment by robvanmieghem** [comment]
TODO:
- [ ] https://github.com/rivine/rivine/issues/347
- [ ] https://github.com/rivine/rivine/issues/348
- [ ] Align the audit command
- [ ] Change  help 
- [ ] Change "Hashed secret"in the outputs to  "Secret hash"
