### ISSUE TITLE
Nodes can be out of sync for long time

### ISSUE THREAD

**Issue by ahussein** [rivine/rivine#364]
We are having a recurring where rivine daemon node is not syncing anymore with its peers and its running behind the rest of the network. @LeeSmet  suggested to using kill -3 $PID and attache the output to this ticket.

This is the list of peers of my current node:
```
root@ubuntu-xenial:~# tfchainc gateway list
3 active peers:
Version         Outbound  Address
1.0.6-alpha  Yes       185.69.166.12:23112
1.0.5           Yes       109.135.19.64:24112
1.0.6-alpha  Yes       185.69.166.11:23112
```
[tfchaind_not_synced.log](https://github.com/rivine/rivine/files/2054177/tfchaind_not_synced.log)

**Comment by LeeSmet** [comment]
What daemon version is this, and is it build in dev mode or release mode?

**Comment by ahussein** [comment]
I do not have that system anymore. I checked and i have a system where its only about 200 blocks behind the explorer height. Should I get the logs from that now ?

**Comment by LeeSmet** [comment]
If the system has the same issue, yes please

**Comment by ahussein** [comment]
Uploaded. The system stayed on the same height since yesterday. Right now it is about 500 blocks behind the explorer node.
[gateway.log.tar.gz](https://github.com/rivine/rivine/files/2083825/gateway.log.tar.gz)

**Comment by LeeSmet** [comment]
Do you by any chance happen to have the output of `tfchainc gateway list`? (or steps to reproduce)

**Comment by ahussein** [comment]
output is:
```
3 active peers:
Version         Outbound  Address
1.0.6-alpha  Yes       109.135.19.64:24112
1.0.6           Yes       185.69.166.11:23112
1.0.6           Yes       185.69.166.12:23112
```

**Comment by LeeSmet** [comment]
Running a vm right now on zero os, will see if I can reproduce

**Comment by LeeSmet** [comment]
2018/06/22 05:48:12.327627 synchronize.go:574: INFO: IBD done, synced with 5 peers.

it took rougly 60hours (debug build, probably writing on the nodes hdd instead of ssd), but synced without problems. Note that it did take around 5.5 seconds on average per block, which can make it look like the IBD stopped. Will see if its feasible to run this on packet.net, since thats the only thing not being done

**Comment by ahussein** [comment]
will debug build take much longer to sync than standard build ?
I am installing two nodes using the make file targets and they are taking a very long time to sync.

**Comment by LeeSmet** [comment]
yes debug takes significantly longer, if you want a 'production' build (which means that lots of debugging checks at runtime are omitted, but this should not be a problem), you'll need to use something like `make install-std`. Also the underlying storage type is important, since syncing does a lot of random reads from the disk and so an ssd is significantly faster than an hdd. On my machine, a debug build with explorer module pulls around 1 block per second (on an ssd), whereas a production build does something of about 10 blocks a second. So it IS really noticeable.

**Comment by LeeSmet** [comment]
@ahussein I was told you have this bug on your dev machine as well? If so, that means you can give me a reproducible scenario?

**Comment by ahussein** [comment]
@LeeSmet I do not know how to reproduce it. I just have it very frequently on my dev machine.
My dev machine has a full node running since quite long time, so I had different versions of the daemons running on it and I usually update the code frequently and run from master branch.

I will be more than happy to provide you with logs, version info and even access to the node in case you need to.

**Comment by LeeSmet** [comment]
Ok, when does it occur? is it after you do something specific (like getting laptop out of sleep mode or something). also how do you identify the problem? e.g. running tfchainc, checking blockheight, then waiting for x amount of time and checking again (if so, how long do you wait). and, does it start to sync again automatically after a while or not?

**Comment by LeeSmet** [comment]
also @ahussein , please provide a copy of the consensus.log file of this daemon

**Comment by ahussein** [comment]
Sorry for my late answer:
attached is the consensus.log file from that out of sync node.
[consensus.tar.gz](https://github.com/rivine/rivine/files/2147011/consensus.tar.gz)

I do not closely monitor the node so I do not know how/when does it occur! and Yes I normally find out the problem i run tfchainc and compare current height with the blockheight on the testnet.
I notice the problem when the difference is high (normally more than 100) and then I keep it checking it for some time.
I am not sure if the node eventually catch up or I always have to restart the daemon. Right now i have a height difference of about 350 blocks. I will not restart my daemon and wait to check how long it will take to sync (if it will even happen).

**Comment by LeeSmet** [comment]
Something that just dawned on me, is it possible that multiple deamons (sometimes) run on the same external IP with the same port?

**Comment by ahussein** [comment]
Yes, I have been running one daemon on my dev machine and additional two daemons in two vms

**Comment by LeeSmet** [comment]
Please run all daemons on the same external IP on a different port, and see if the issue is still present then.

**Comment by ahussein** [comment]
Ok, done that. Will update the ticket once i have more info

**Comment by ahussein** [comment]
@LeeSmet After changing the port of each daemon, and since yesterday all my nodes are synced and I do not have any node that is lagging behind.

**Comment by GlenDC** [comment]
That's great news. Keep doing that. If no sync issues arise by the ending of next week, we can safely assume that we found the origins of your issue I would say. For now it seems to early to tell for sure, even though it is already very likely.

**Comment by ahussein** [comment]
I have been checking on my nodes every now and then and I did not notice the problem happening anymore. I would conclude that running the daemons on the same <external_ip>/port was the reason for the problem.

I am not sure how you guys want to handle this. But at least there should be something in installation docs or the Q/A section about this issue.
