### ISSUE TITLE
support `-y/--yes` global flag to the atomicSwapCmd

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#365]
When this (boolean) flag is defined as `true`, it should prevent any Y/N questions being asked to the user in the atomic swap commands.

The global flag can be added to `atomicSwapCmd ` using https://godoc.org/github.com/spf13/cobra#Command.PersistentFlags, and calling the BoolVarP method on that returned flag set (see other flags in our client code to see our conventions about how to define these flag properties and such).

Once this flag is added we want to put an `if !atomicSwapcfg.YesToAll {}` check around following code blocks: 

+ https://github.com/rivine/rivine/blob/a4d74b1139ee4f0918c74d59a7d919a73f086323/pkg/client/atomicswap.go#L217-L224
+ https://github.com/rivine/rivine/blob/a4d74b1139ee4f0918c74d59a7d919a73f086323/pkg/client/atomicswap.go#L590-L597

This check will ensure two things:

1. To not print the contract to STDOUT, and thus not interfering with the regular output, a very important thing for an automated environment;
2. To not ask a Y/N question and simply assume Yes instead for this question, as indicated by the `-y/--yes` flag;

This issue has to be resolved should you want to use the atomic swap commands in an automated environment.

**Comment by jdelrue** [comment]
Code for this is ready. Will do pull request today!

**Comment by jdelrue** [comment]
Why don't we adjust

``
func askYesNoQuestion(str string) bool {
``

so it returns the value? This way we don't have to include a check in every individual code block.

If we don't print to std::out, how will we ever interpret (json) output in an automated environment?

**Comment by jdelrue** [comment]
Impl ready and pushed, will test this afternoon

**Comment by GlenDC** [comment]
You proposed earlier to put the `YesToAll` property check in the `askYesNoQuestion ` function (https://github.com/rivine/rivine/blob/84349693e539652219bbb7d94f911244c4ffbec4/pkg/client/atomicswap.go#L716), at the top, and yes I agree with that. Feel free to put an `if yesToAll { return true }` check at the top.

I thought about this before, but at that point it made sense to me to not print the contract review. However, that does mean that you wan to ensure that https://github.com/rivine/rivine/blob/84349693e539652219bbb7d94f911244c4ffbec4/pkg/client/atomicswap.go#L218-L219 is only executed when the encodingType is `human` (a check possible for when #366 is (being) resolved).

Same goes for https://github.com/rivine/rivine/blob/84349693e539652219bbb7d94f911244c4ffbec4/pkg/client/atomicswap.go#L592-L593.
