### ISSUE TITLE
support JSON outputs of atomic swap commands

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#366]
We can achieve this by:

1. adding a persistent flag (`--encoding`) to the `atomicSwapCmd` using https://godoc.org/github.com/spf13/cobra#Command.PersistentFlags, and calling the `Var` method on that returned flag set (see the explore.go file and the consensus's transaction CLI command of examples on how to register a `cli.EncodingType` as a `EncodingTypeFlag` using that `Var` method, as mask you'll want to use `EncodingTypeHuman | EncodingTypeJSON`, as to not allow hex encoding, given it doesn't make any sense here)
2. defining structures with JSON annotation tags for each output type, as a public type, so these are included in the documentation, you'll need one for each command
3. adapt the command methods, such that where we output data to the STDOUT, we first switch on the `atomicSwapcfg.EncodingType` property, prior to printing. If it equal the `EncodingTypeHuman`, we would print in the human STDOUT format we currently use, a very custom but readable one, but if it's `EncodingTypeJSON`, we would print using the correctly defined struct, defined for this JSON-encoded printing purpose only. You'll need to do this in the following places:
    1. outputID+transactionID of created contract @ https://github.com/rivine/rivine/blob/a4d74b1139ee4f0918c74d59a7d919a73f086323/pkg/client/atomicswap.go#L251
    2. audited contract's properties and value @ https://github.com/rivine/rivine/blob/a4d74b1139ee4f0918c74d59a7d919a73f086323/pkg/client/atomicswap.go#L341 (and print those optional validation error messages below in the STDERR instead of STDOUT, no matter the encoding format, so that STDOUT/STDERR separation is properly done there)
    3. secret, extracted from contract @ https://github.com/rivine/rivine/blob/a4d74b1139ee4f0918c74d59a7d919a73f086323/pkg/client/atomicswap.go#L496
    4. transactionID from transaction used to redeem/refund  contract @ https://github.com/rivine/rivine/blob/a4d74b1139ee4f0918c74d59a7d919a73f086323/pkg/client/atomicswap.go#L636

This issue has to be resolved should you want to use the atomic swap commands in an automated environment. Should you resolve this issue together with #365, you'll be able to use the atomic swap commands in an automated environment.

**Comment by jdelrue** [comment]
GlenDC:

The way I solved it in the current version:
- Added a printer.go file that contains human readable and json name for each printerproperty
https://github.com/JimberSoftware/rivine/blob/master/pkg/client/printer.go

- Called the print action from this file instead of println, in printer.go the flag is checked so it will print json if the flag is set or human readable otherwise

- Adjusted "die" method  in the printer.go so it prints json if needed

Please review here:
https://github.com/JimberSoftware/rivine/blob/master/pkg/client/printer.go

And here:
https://github.com/JimberSoftware/rivine/blob/master/pkg/client/atomicswap.go

If you want me to use switch in the atomicswap file instead I can implement it, but I think this solution keeps atomicswap.json clean. I will change the flags to cli.EncodingType and EncodingTypeHuman | EncodingTypeJSON

**Comment by GlenDC** [comment]
I saw your code in the meeting, but it's an approach I do not agree with. You have an entire system setup there in a way I would call overkill. It's simple enough to provide different printing depending on what encoding type, and on top of that it gives a lot more flexibility, which is useful for non-json encoding types. On top of that there is no need to print the Die message in a JSON format. This is meant as an error message and thus prints to STDERR. In which case a non-0 exit code is returned, which should mean you do not care about any possible output at all, at least in our CLI that is the convention. Your proposed JSON format is also overly generic, with an action and data, which is really not needed. When I call a CLI command, I only expect one successful output format, so I would just like to receive that format, rather than first having to check that action property first.

The CLI code we really try to keep as simple as possible.

For example, for the redeem/refund methods it could be as simple as:

```go
type (
   // AtomicSwapRedeemRefundOutput is the robot-friendly output format,
   // for the AtomicSwap Refund and Redeem commands, in case of a successful outcome.
   AtomicSwapRedeemRefundOutput struct {
      TransactionID types.TransactionID `json:"transactionid"`
   }
)
```

```diff
diff --git a/pkg/client/atomicswap.go b/pkg/client/atomicswap.go
index bbbab40..1b08f30 100644
--- a/pkg/client/atomicswap.go
+++ b/pkg/client/atomicswap.go
@@ -633,6 +633,14 @@ func spendAtomicSwapContract(outputID types.CoinOutputID, secret types.AtomicSwa
 		Die("failed to "+keyWord+" atomic swaps locked tokens, as transaction couldn't commit:", err)
 	}
 
+	if atomicSwapcfg.EncodingType == cli.EncodingTypeJSON {
+		// return the transactionID as part of a JSON struct,
+		// such that it can sanely be consumed in an automated environment
+		json.NewEncoder(os.Stdout).Encode(
+			AtomicSwapRedeemRefundOutput{TransactionID: txnid})
+		return
+	}
+	// return the transactionID to a human audience, packaged with a warning
 	fmt.Println("")
 	fmt.Println("published atomic swap " + keyWord + " transaction")
 	fmt.Println("transaction ID:", txnid)
```

As you can see from my example, that code is still very simple. On top of that, it is much more easy to understand this kind of code, if the data structure lives together with the actual logic. Understanding this code is also simple, given you just need to read, and can however/click-through the structure to understand that format instantly as well. While in your proposed over-generic system, I really need some time in order to understand it.

**Comment by jdelrue** [comment]
I would keep the way you print the output seperated from the logic. You can add any type of printing in the same file. But its your codebase so no problem, I will adjust the output the way you propose.
