### ISSUE TITLE
Possible to include transactions with less fee than the minimum fee

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#389]
Example of such a transaction: 
https://explorer.testnet.threefoldtoken.com/block.html?height=8120

Possible cause:

https://github.com/rivine/rivine/blob/master/modules/transactionpool/accept.go#L75

**Comment by GlenDC** [comment]
@robvanmieghem please provide input when you can.

**Comment by robvanmieghem** [comment]
I've said before that transaction fees are not checked properly.The transactionpool should not be the only place to validate transaction fees.  While free transactions might be beneficiary, it should be implemented properly with a clear strategy, the current implementation is rather poor imho and not the way we intended it anyway.

**Comment by robvanmieghem** [comment]
@GlenDC  Please stop cluttering issues with calls for attention  within the first few hours after creation.

**Comment by GlenDC** [comment]
How did we intend it?

**Comment by robvanmieghem** [comment]
a fixed minimum fee  and if the block is full, include the ones with the highest fee

**Comment by GlenDC** [comment]
Yeah OK. So than the approach here would be to already ensure the fixed minimum fee is guaranteed at all times by both the pool and the consensus. On top of that we can add a new feature request to sort based on the highest fee when it is full. I would like to move that feature request to a future milestone though, as that one only makes sense if our wallets somehow can also increase/set the transaction fee, perhaps even automatically guess a proper amount that would give it guarantees it will be included.

**Comment by LeeSmet** [comment]
It seems that currently the transaction pool size is limited to 2MB, which is (likely, since its configurable) less than the maximum block size. So if we implement the sorting based on fee value (or better, fee per byte), we should also see about increasing the size of the transaction pool

**Comment by GlenDC** [comment]
Makes sense.

In next release we can do both things I suppose:

+ Enforce from a certain block height that at least the minimum  transaction fee is defined for every transaction (to be done as solution for this issue);
+ Add some non-enforced logic to make the transaction pool sort the transaction based on fee-per-byte, such that it can prioritize when needed (feature request issue has to be made, as it is out of scope for this issue);

**Comment by GlenDC** [comment]
> Add some non-enforced logic to make the transaction pool sort the transaction based on fee-per-byte, such that it can prioritize when needed (feature request issue has to be made, as it is out of scope for this issue);

Moved to issue #394
