### ISSUE TITLE
Consensus synced property does not update in some setups

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#397]
In case a node is connected to many local peers (which might also not be synced), there are situations where a node's consensus set `synced` property never becomes `true`. As a result, these nodes won't create blocks.

This probably has to do with this check during the IBD:
https://github.com/rivine/rivine/blob/master/modules/consensus/synchronize.go#L573

**Comment by LeeSmet** [comment]
At the time there was only 1 public node on the testnet. As soon as more public nodes came online, this resolved itself. Given that 1 public node can be considered an issue in itself, I'm not sure if we want to do anything here

**Comment by GlenDC** [comment]
Feel free to close this as `wontfix` for now.
