### ISSUE TITLE
use xtaci/smux instead NebulousLabs/muxado

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#41]
`Muxado` is a dependency used in the gateway module, and handles all the underlying peer connections, as it acts as our stream multiplexer. NebulousLabs is using a forked version, which I assume is because they want to stick with version 1 of `muxado`. The original repo is in the meanwhile on version 2, 30 commits later.

As `Muxado` is a very important piece in the gateway puzzle, it might be worth investigating (eventually) and choose to update this dependency to the latest version of the original repo, and update the code accordingly.

Before this is done however, should have sufficient reasons and arguments that support this action.

**Comment by GlenDC** [comment]
It seems like Sia was planning to switch to V2 for a long time now. But in the meanwhile they have decided that they actually want to go for https://github.com/hashicorp/yamux instead. So it might be interesting for me to help them integrate it into Sia, and then merge that over to here.

**Comment by GlenDC** [comment]
hashicorp/yamux is inactive. Instead we'll go for https://github.com/xtaci/smux.

**Comment by robvanmieghem** [comment]
Moving to milestone 0.1.1 since this would fix #51
