### ISSUE TITLE
the explorer should show more details of a multisig address

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#419]
when showing the coin outputs of a multisig address like https://explorer.testnet.threefoldtoken.com/hash.html?hash=032aa4d45db439b02d00e26990369281c83da55c111c3a4cc8c43e951324d3794bd62ed7d909b2

You can not see it is a multisig  while the coin output itself  does show all details:
https://explorer.testnet.threefoldtoken.com/hash.html?hash=fdfd50902be19f73152f9ef62bb25b9da3c69179ce44d18c05f3c390796ad557

**Comment by GlenDC** [comment]
Moved to tfchain, as this is a web-explorer issue, not a rivine daemon explorer module issue.
