### ISSUE TITLE
improve gateway code

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#42]
After a discussion with the Sia developers, it seems like I might be able to start improving the gateway code together with them, as a lot of what I had in mind was already on their TODO list since a long time. Their entire list can be found on https://github.com/NebulousLabs/Sia/projects/2

Here is what I propose to be working on, such that this can be merged asap to rivine:

- [ ] Integrate xtaci/smux into gateway, replacing muxado v1, which is outdated, not supported and potentially buggy (issue #41);
- [x] Improve documentation for the encoding, rpc and messaging. Right now you have to almost reverse engineer what all the RPC operations are, how they are decoded and how they work. Having documentation for this would help a lot for anyone to quickly jump into this code. On top of that it would also allow us to write clients in different languages easily, if this would be needed;
- [x] making sure two different networks running our code will not have their peer networks hooking together (this would be done by having some kind of Network ID. related to NebulousLabs/Sia issue 1480);
- [x] have a unique ID per gateway (and thus node and peer), this would allow gateways to detect whether they are connecting to themselves or not (which is possible in case they are from the same home network, and thus having the same external IP) (this unique ID would not be persistent, and has nothing to do with storing peers, it is only used to identify connections to itself);
- [ ] any TODO that I can tackle while doing other issues, or that seem priority enough (for example a list of todo's can be found at [modules/gateway/gateway.go#L71-L135](https://github.com/NebulousLabs/Sia/blob/master/modules/gateway/gateway.go#L71-L135));

Other tasks that are nice to have:

-  eclipse attacks + peer anchoring (need to read up on this a lot: https://eprint.iacr.org/2015/263.pdf, https://www.eecs.harvard.edu/~mema/courses/cs264/papers/eclipse-infocom06.pdf, https://homepage.cs.uiowa.edu/~ghosh/P2P_Attacks.ppt, https://eprint.iacr.org/2015/796.pdf);
- The set of bootstrap nodes needs to be monitored and nodes with low uptime should be removed (NebulousLabs/Sia issue 1481);

I'm in direct contact in a private chat with the 3 relevant core developers, so they will give me feedback as I go and help ensure the quality. In the future we might want to do extra changes _just_ in rivine, as those would break Sia. However I think this would be enough to get us started, and is all in line with the sia version 1.3, planned to be released in 3-6 months.

**Comment by GlenDC** [comment]
Integrated yamux: https://github.com/GlenDC/Sia/commit/78dc0f5d5dfcc605fce6483824ef9488a818a048

To be perfect we might want to fix issue 37 of hashicorp/yamux, and make their Read/Write errors return a `net.Error`, such that we can better check timeout errors. But for now it's OK as it is I think. Already forked yamux, so might do that later when I have time.

**Comment by GlenDC** [comment]
Updates to handshake protocol are in progress in Sia. This will add the UniqueID and NetworkID to the handshaking, right after the version exchange. When this all get merged into Rivine, we should also take the opportunity to clean up that code, merge different parts together, as we do not have to worry about breaking clients for now, which Sia does have to worry about. On top of that we should also ensure that the handshake protocol as it is, is extensible enough, for any future requirements.

**Comment by GlenDC** [comment]
RPC Documentation has been added and merged into Sia's master branch: https://github.com/NebulousLabs/Sia/blob/master/doc/RPC.md

**Comment by robvanmieghem** [comment]
@GlenDC Closing this issue since the open taks are referenced in different issues.
