### ISSUE TITLE
explorer should index multisig addresses to wallet addresses

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#420]
The explorer should index all multisig addresses to wallet addresses. This should make it easier to know for a given wallet address, if it is also part of a multisig wallet.

**Comment by GlenDC** [comment]
FYI @robvanmieghem: changed the issue title and description.

Discussed it with @LeeSmet as well. It didn't seem very useful to index these transaction ids to the individual unlock hashes as well, as it would mean that when looking an unlock hash up, you will always get all transactions, even the multistig addresses. This might not be desired, and even if it is desired, it wouldn't be useful as it is, as you would probably want to sort per address (unlockhash) anyhow.

Instead we'll just return multisig addresses found for a given unlock hash, as a array. The client can than still do other requests to get the transactions for the given multisig address(es) should it want to (as separate calls).

**Comment by GlenDC** [comment]
On tfchain master the web explorer has already been improved, as part of the upcoming release. For example there is more information visible for a given wallet address already:

<img width="1072" alt="screen shot 2018-07-31 at 21 35 49" src="https://user-images.githubusercontent.com/3900482/43482735-cf0d6e2c-9509-11e8-9c00-f899645315f2.png">

Once the daemon explorer returns the multisig address slice as part of a UnlockHashGET call, we can —iff the wallet address is part of one or more multisig wallets— add some wallet stats to the bottom of the table, listing those multisig addresses. The user can than click through any multisig address, and will see a page such as:

<img width="1180" alt="screen shot 2018-07-31 at 21 39 26" src="https://user-images.githubusercontent.com/3900482/43482865-38d5c1ba-950a-11e8-8b4c-ec330678773c.png">

**Comment by GlenDC** [comment]
Rivine/Tfchain Daemon Explorer returns (on rivine/tfchain master and multisig addresses of multisig wallets a wallet address is part of. The tfchain web explorer visualises these now on (tfchain) master as well.

**Comment by GlenDC** [comment]
Example On Web Explorer

<img width="1051" alt="screen shot 2018-08-02 at 11 05 26" src="https://user-images.githubusercontent.com/3900482/43574267-fef15bae-9643-11e8-8e8e-ae8fc0992478.png">

Same explorer but as the raw daemon JSON output:

```
$ tfchainc explore hash 01c1f24eb0792086567fe9e2b8d6c2a66cca733be2518fbac22ec8793da3b00b0759d37b6100bf
{
  "hashtype": "unlockhash",
  "block": {
    "minerpayoutids": null,
    "transactions": null,
    "rawblock": {
      "parentid": "0000000000000000000000000000000000000000000000000000000000000000",
      "timestamp": 0,
      "pobsindexes": {
        "BlockHeight": 0,
        "TransactionIndex": 0,
        "OutputIndex": 0
      },
      "minerpayouts": null,
      "transactions": null
    },
    "blockid": "0000000000000000000000000000000000000000000000000000000000000000",
    "difficulty": "0",
    "estimatedactivebs": "0",
    "height": 0,
    "maturitytimestamp": 0,
    "target": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "totalcoins": "0",
    "arbitrarydatatotalsize": 0,
    "minerpayoutcount": 0,
    "transactioncount": 0,
    "coininputcount": 0,
    "coinoutputcount": 0,
    "blockstakeinputcount": 0,
    "blockstakeoutputcount": 0,
    "minerfeecount": 0,
    "arbitrarydatacount": 0
  },
  "blocks": null,
  "transaction": {
    "id": "0000000000000000000000000000000000000000000000000000000000000000",
    "height": 0,
    "parent": "0000000000000000000000000000000000000000000000000000000000000000",
    "rawtransaction": {
      "version": 0,
      "data": {
        "coininputs": [],
        "minerfees": null
      }
    },
    "coininputoutputs": null,
    "coinoutputids": null,
    "coinoutputunlockhashes": null,
    "blockstakeinputoutputs": null,
    "blockstakeoutputids": null,
    "blockstakeunlockhashes": null
  },
  "transactions": null,
  "multisigaddresses": [
    "032aa4d45db439b02d00e26990369281c83da55c111c3a4cc8c43e951324d3794bd62ed7d909b2",
    "037504aa43000316da59c1f3c16deaabac860e18f7bf943d4f42706ce61f9d61ad73417f15c8df",
    "0385abdb2b42ad33df6e9ff1ff3f05d709b6e604b9966e29d801895631dbf296de744b50a17af1",
    "03d713b9407c61e7910e586932628580dc8e35ea50714cad00ccd091f389ebdb8a8f7cb28a4841"
  ],
  "unconfirmed": false
}
```
