### ISSUE TITLE
explorer: unclear parent id label

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#435]
Change the parent id label in an input to "Used output"
<img width="312" alt="screen shot 2018-08-06 at 13 31 40" src="https://user-images.githubusercontent.com/3511318/43714458-560b4012-997d-11e8-99ff-524be8694e90.png">
It would make it a lot more clear to people who do not know the internal datastructures

**Comment by GlenDC** [comment]
fixed in tfchain: https://github.com/threefoldfoundation/tfchain/commit/6cd03ba93aea7b147e9941f75c7b9dd27be576c6
