### ISSUE TITLE
Explorer module: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#437]
2018/08/09 10:17:32 http: multiple response.WriteHeader calls
2018/08/09 10:20:21 http: multiple response.WriteHeader calls

**Comment by GlenDC** [comment]
Might be similar to <https://github.com/rivine/rivine/issues/369>.

**Comment by GlenDC** [comment]
I don't think this is still an issue in the current codebase.

I tried to reproduce it by triggering REST API calls (correct ones as well as incorrect calls) on devnet, and nothing out of the ordinary was spotted.

Scanning the code base for all places that write HTTP headers in our REST API server logic (e.g. using a regexp such as `(WriteError|WriteSuccess|WriteJSON)\(`, also doesn't show a spot where write a header, without returning afterwards. So I do not see how that (innocent) error could still be triggered either.

Going to close it therefore, if you (or someone else reading this) does run into this error again in a log, please do reopen this issue and do so while telling which REST API calls you have triggered.
