### ISSUE TITLE
Pull in SIA improvements

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#46]

**Comment by GlenDC** [comment]
The Smux PR in Sia is about to be merged in so, I can fix issue #41 as part of this issue. Also I need to think about a merging strategies that works for us. Last time I simply merged files over from Sia, but I don't think that's a viable strategy that I can keep doing. So I'll need to:

+ list what SIA improvements we to pull in (certainly bug fixes, but then also check what features we might want);
+ figure out how we can easily merge in such changes, that go beyond just merging files over by hand;

**Comment by GlenDC** [comment]
smux is already integrated as well into rivine.

All the other work is split up in the following issues: #79, #80, #81, #82, #85 and #86.
