### ISSUE TITLE
Easier chain configuration

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#53]
Currently the chain parameters are defined in [types/constants.go](https://github.com/rivine/rivine/blob/master/types/constants.go). When you want to start a chain with different parameters, this only leaves the option of forking and modifying the code. I think there are two options, either we make this configurable in an external config file or we make the rivine code importable in a different project and allow for easy injection of these variables. Lets go for the second option.

**Comment by LeeSmet** [comment]
Partially done, some improvements that still could be done:

Refactor the actual commands in the rivined package to not depend on a config, but take the exact parameters. Then they can also be exported to allow for some more customization. Also right now the constants (mainly related to genesis) must be set explicitly with calls to the exported variables in the types package, which is easy to miss one. So some methods which help with this might be a solution here

...

**Comment by robvanmieghem** [comment]
@LeeSmet Can  you create seperate issues for this in the backlog milestone so we can close this issue?

**Comment by LeeSmet** [comment]
Separate issue created: #100, work for this one done in d8aef1862794e6e5f6ba6fea70d07817a2caf47a
