### ISSUE TITLE
Questions to clarify in documentation

### ISSUE THREAD

**Issue by nbabenko** [rivine/rivine#56]
1. Who exactly are signing blocks? How the BlockStakes are distributed? 
2. Who controls initial supply and distribution of BlockStakes?
3. Can new nodes join block signing? Ways for new actors to become participants in consensus. 
4. Are blockStakes freely transferrable?
5. What are possible attack vectors on the network? (Cases in which it is theoretically possible for a malicious actor to get control of the network). What are our countermesures for these cases if any?
6. More details how to launch new chain and where/how to write consensus contracts/logic 
7. Protocol upgrade logic
8. Roadmap for further development/current bottlenecks

**Comment by GlenDC** [comment]
Most of these questions can be answered from a Rivine perspective, but some of them really do need to be documented in tfchain instead, as the blockchain implementation decides in this matter a lot. Following will need to be answered in the tfchain repo:

+ (1) Who exactly are signing blocks? How the BlockStakes are distributed?
+ (2) Who controls initial supply and distribution of BlockStakes?

> Issue threefoldfoundation/tfchain#59 has been opened for this one.

(1), (2), (3), (4) and (5) are already partly answered in [/doc/ProofOfBlockStake.md]. Might need to give more information here. Have tasked specific issues for these as #252 and #253.

Following question is very vague, and is handled by planned milestones and issues, I don't see a need to add documentation for this, as this is what milestones and issues are made for:

+ (8) Roadmap for further development/current bottlenecks

(6) and (7) do still need documentation. Have planned those as tasks for next milestone: #254 and #255
