### ISSUE TITLE
Smart contract definition

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#57]
Before we can even start thinking about implementing "smart contracts", we need to have a clear definition what a smart contract is and what capabilities a smart contract should have

**Comment by robvanmieghem** [comment]
since a rivine chain is application sprcific,  do we need everyone to be able to supply new contract code and be a smart contract platform or not?

**Comment by zaibon** [comment]
> since a rivine chain is application specific, do we need everyone to be able to supply new contract code and be a smart contract platform or not?

What would be the implication if we decide to be a platform that support new contract.
Having this support in mind from day one would make our life easier when we change/add new contract for our use cases as well, no ?

**Comment by robvanmieghem** [comment]
@zaibon do not underestimate the complexity and potential bugs and security issues(cfr ethereum smartcontract hacks)

**Comment by robvanmieghem** [comment]
closing this issue, smart contracts should be hardcoded
