### ISSUE TITLE
revive Travis CI

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#68]
+ [x] first we need to make sure all enabled unit tests compile & pass (see: #38);
+ [x] than we'll want to make sure the travis Config is correct;
+ [x] as an extra we can also add some extra CI scripts to check stuff like vetting, fmt, linting;

**Comment by robvanmieghem** [comment]
some packages already have fixed unit tests:
https://github.com/rivine/rivine/issues/38#issuecomment-364531925

**Comment by GlenDC** [comment]
Yes perfect, as soon as I've merged #75, I'll enable travis with all possible tests already.
