### ISSUE TITLE
integrate the publish script in the makefile as a publish target

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#76]
and add zero-os container image creation

**Comment by LeeSmet** [comment]
For now I added a rule which creates a minimal docker container with the linux release binaries, which depends on the `xc` rule (so the tarballs for the different os will also be created), and pushes the container to dockerhub. I'll add the zero os container image once I figure out how to do that (i.e. once I get a hold of maxime)

**Comment by LeeSmet** [comment]
Modified the xc target to actually create a docker `builder` and build the binaries in those. This ensures the same build setup accros different machines

**Comment by LeeSmet** [comment]
Maxime will expose an api endpoint on the hub which converts a docker image to an 0-os flist. Then we only need to set a variable with a valid JWT before calling make. This is imo the best solution at the moment for the 0-os container image. (A front end endpoint is already available for this but those are not stable, hence I'll wait for the api endpoint)
