### ISSUE TITLE
speakeasy library is not vendored

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#78]
after `make ensure_deps`

rivinec/main.go:12:2: cannot find package "github.com/bgentry/speakeasy" in any of:
        /go/src/github.com/rivine/rivine/vendor/github.com/bgentry/speakeasy (vendor tree)
        /usr/local/go/src/github.com/bgentry/speakeasy (from $GOROOT)
        /go/src/github.com/bgentry/speakeasy (from $GOPATH)

**Comment by GlenDC** [comment]
It's vendored as part of #77.
