### ISSUE TITLE
merge desired sia/modules/explorer changes into rivine/modules/explorer

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#86]

**Comment by GlenDC** [comment]
Are you already working on this one @robvanmieghem, otherwise I don't mind doing it, as it is quite related to some of the other modules still to be merged.

**Comment by robvanmieghem** [comment]
Skipped e7116668dba6636feb73e47a8befcbdc443eef2f since it's main impact is in the consensus module

**Comment by GlenDC** [comment]
> Skipped e711666 since it's main impact is in the consensus module

Let's not forget that to do as part of #85 in that case. But I guess that will be clear enough due to the commit history.
