### ISSUE TITLE
look at sia bbolt modifications

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#98]
Sia modified the vendored bbolt like in commit ec535f7c2a0b5bad406779309c2eb5232f068204

**Comment by GlenDC** [comment]
OK, so there are 2 things. First of all, I seem to have vendored a pretty old version, from 2016, not sure why `golang/dep` vendors that version by default. So we'll have to sync with master first, as Sia is up to date with latest master.

The commit you mentioned seems to be the only commit in which they've modified the vendored version (on a sidenote, they only vendor dependencies when they modify them, so we might want to check the other dependencies as well, I'm not a big fan of modifying the vendor dir though, as such changes can be easily overwritten, I would prefer a vendored fork instead).

In that commit they claim to have simply added a `MmapError` to indicate the mmap'ing of some data failed, however, they are also doing some extra mmap'ing back to the minimum required size prior to that. We'll have to investigate why they did this second part of the change, even though the comment also explains a bit.

The `MmapError` they use in the consensus to indicate the system is out of memory. So for now we don't really need it. We could resolve this issue together with #85.

**Comment by robvanmieghem** [comment]
> I'm not a big fan of modifying the vendor dir though, as such changes can be easily overwritten, I would prefer a vendored fork instead).

same way I feel about it

**Comment by GlenDC** [comment]
In 1.0.1, we'll fork bbolt, and apply the changes there. We could try get it upmerged if it makes sense. For now we should leave it as it is. See #218 for more info.
